In [15]:
#1-Importando as bibliotecas - Pandas e Selenium 

import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

#Selenium precisa de um outro código para usar, o from diz um livro da biblioteca Selenium
#Chrome: navegador utilizado
#Baixar crhomedriver 97 colocálo em uma pasta dentro da pasta que contém o python

#2-Abrindo o Chrome e pesquisar e pegar a cotação de dólar
navegador = webdriver.Chrome()
navegador.get("https://www.google.com/")

#Get(<site>): Método que realiza acesso à página

navegador.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação dólar")
navegador.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

#Depois de abrir o Chrome, localizar a barra de pesquisa, para isso, deve-se clickar com o botão direito do mouse; inspecionar; clickar na barra de pesquisa; clickar com botão direito no código; copy; copy full xpath
#Find_element: busca o método para selecionar a barra de pesquisa
#/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input: código Xpath
#.send_keys: digita o texto quando usa "" e aperta tecla quando usa Keys.

cotacao_dolar = navegador.find_element(By.XPATH, '/html/body/div[7]/div/div[10]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div[3]/div[1]/div[1]/div[2]/span[1]').get_attribute("data-value")
print(cotacao_dolar)

#'data-value': atributo mostrado pelo código HTML que recebe o valor cotação

#3-Abrindo o Chrome e pesquisar e pegar a cotação do euro

navegador.get("https://www.google.com/")
navegador.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação euro")
navegador.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
cotacao_euro = navegador.find_element(By.XPATH, '/html/body/div[7]/div/div[10]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div[3]/div[1]/div[1]/div[2]/span[1]').get_attribute("data-value")
print(cotacao_euro)

#4-Pesquisar e pegar a cotação do ouro

navegador.get("https://www.melhorcambio.com/ouro-hoje")
cotacao_ouro = navegador.find_element(By.XPATH,'/html/body/div[5]/div[1]/div/div/input[2]').get_attribute("value")
cotacao_ouro = cotacao_ouro.replace(",",".")
print(cotacao_ouro)
navegador.quit()

#cotacao_ouro.replace(",","."): é preciso alterar separador de casas decimais para o do python (,para .)
#navegador.quit(): fecha o navegador

#5-Importando a planilha Excel

tabela = pd.read_excel(r'C:/Users/Computador/Desktop/Gabriel/Análises, Economia, Finanças, Empreendedorismo, Investimentos e Programação/Programação/Python/Hashtag/Produtos.xlsx')
display(tabela)

#6-Atualizando a planilha Excel

tabela.loc[tabela["Moeda"] == "Dólar", "Cotação"] = float(cotacao_dolar)
tabela.loc[tabela["Moeda"] == "Euro", "Cotação"] = float(cotacao_euro)
tabela.loc[tabela["Moeda"] == "Ouro", "Cotação"] = float(cotacao_ouro)
display(tabela)

#tabela: modificação serpa no dataframe tabela
#.loc: permite selecionar apenas linhas que atendam ao requisito de ter "Dólar" na coluva Moeda
#Cotação: Encontradas as linhas que possuem “Dólar” na coluna “Moeda”, o Loc irá alterar a coluna “Cotação”

tabela["Preço Base Reais"] = tabela["Preço Base Original"] * tabela["Cotação"]
tabela["Preço Final"] = tabela["Preço Base Reais"] * tabela["Ajuste"]
display(tabela)

#As colunas que dependem das variáveis não foram alteradas junto, portanto devemos alterar

#8-Exportando os dados

tabela.to_excel("Produtos Novo.xlsx", index=False)

#Produtos Novo.xlsx: nome do arquivo criado
#index=False: Indica que não deverá ser exportada a coluna com o índice das linhas

5.303061
5.494766655
304.24

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Ajuste,Preço Final
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Ajuste,Preço Final
0,Câmera Canon,999.99,Dólar,5.303061,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,5.494767,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5.303061,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5.303061,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,5.494767,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5.303061,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,304.240000,7000.00,1.15,8050.000

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Ajuste,Preço Final
0,Câmera Canon,999.99,Dólar,5.303061,5303.007969,1.40,7424.211157
1,Carro Renault,4500.00,Euro,5.494767,24726.449948,2.00,49452.899895
2,Notebook Dell,899.99,Dólar,5.303061,4772.701869,1.70,8113.593178
3,IPhone,799.00,Dólar,5.303061,4237.145739,1.70,7203.147756
4,Carro Fiat,3000.00,Euro,5.494767,16484.299965,1.90,31320.169934
5,Celular Xiaomi,480.48,Dólar,5.303061,2548.014749,2.00,5096.029499
6,Joia 20g,20.00,Ouro,304.240000,6084.800000,1.15,6997.520000

In [7]:
pip install -U selenium

Requirement already satisfied: selenium in c:\users\computador\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\computador\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio~=0.17 in c:\users\computador\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\computador\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\computador\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: idna in c:\users\computador\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: outcome in c:\users\computador\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\computador\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.0.1)
Requirement already satisfied: sortedcontainers in c:\users\computador\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\users\computador\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\computador\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\users\computador\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\computador\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\computador\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\computador\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\computador\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\computador\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip freeze
#Mostra as bibliotecas do Jupiter